name: Build and push image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      -
        name: Just some text
        run: echo "starting compile"
      -
        name: List files
        run: |
          pwd
          ls -lhr

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
