name: Build and push image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/resume ./src/*.go

      - name: List files
        run: |
          echo "---------------------------------------------------------------------------------"
          pwd
          echo "---------------------------------------------------------------------------------"
          ls -lhr .
          echo "---------------------------------------------------------------------------------"
          ls -lhr /
          echo "---------------------------------------------------------------------------------"

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
