name: Build and push image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-binary:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      - name: Pushing the freshly built image
        run: |
            echo "Inside group"

  build-dockerfile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rogierlommers/resume:$(date +%s)

  push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      - name: Pushing the freshly built image
        run: |
            echo "Inside group"
